name: terminal
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  dio: ^5.0.0
  firebase_core: ^2.4.1
  firebase_database: ^10.0.10
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.0+1
  google_fonts: ^4.0.1
  intl: ^0.18.0
  sunmi_printer_plus: ^2.1.01
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
